on:
  push:
    branches:
      - develop
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VS_MARKETPLACE_TOKEN"
        env:
          VS_MARKETPLACE_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}